language: go
go:
  - 1.7

script:
  - make build
  - make test

before_deploy: make release-build

deploy:
  provider: releases
  api_key:
    secure: dg0LYigX/6Ee2T8yVcamwoXyzxZxeb4t4foPE5D5UV9FnW4SFpGLe2pp+ip02YcF+Ky2e9XoCp2wUDbGbdmKw9dDtgxoX4IQPf/VADfp9jwxj/jdWVLLeP6dCH2oJenuFE/5RipWF1P/zwZhplArgb+R5HL6nlFslf9D3tgeENiRu8oDHF9OrvxIBp/QQFf+dmZWznovkmjdyw2HUOkOUX1ThoxNElV9DDNgeKuTTYU03hWiLgGV4T8EZtpNIrCG+hYbpA0Ul29TfGQIdGeKx0B2mVcawXIS57L3HC0R1KNRRAMMDcOdQ2xcAYp28NljNPFsFDU3Ym8X7cAhwMA5kc4SgKqwffeNHQiAVgoxnoiyGXiAg3M8q0+42dGpwBBQD480RFGKISkca7CGzxoJ2ymiVl6PcfTZnS0ixShjAIH5IA32zrmfxXBGLjlUGn7oIJM0GEYHrpykTpAlK2ZJ0C85HOOn789bk3F58CwljpDE0VufoynQZ5s7qdacu4eDTPBebfGeOh2FoFv+NCyl1qRHrQtU7eUtIADQgs6GTMKJPbeCCFPOLw7i8D9rxOeLJr1tLyvjVgJH0yHmzF3ePvzLUxmeeg5p3tPW02KCd9YBQl1RSGZYULE77/Q0/qy9H0bcvG3ZjK65kjt7NzWTEwM8tvXU8lcPgCdQDA0/kwQ=
  file:
    - build/nsq_exporter_darwin_amd64
    - build/nsq_exporter_freebsd_386
    - build/nsq_exporter_freebsd_amd64
    - build/nsq_exporter_linux_386
    - build/nsq_exporter_linux_amd64
    - build/nsq_exporter_linux_arm
    - build/nsq_exporter_linux_arm64
    - build/nsq_exporter_windows_386.exe
    - build/nsq_exporter_windows_amd64.exe
  on:
    repo: lovoo/nsq_exporter
    tags: true
